version: "2"

services:

  redis:
    image: redis:3.2-alpine
    ports:
      - "6379"
    networks:
      - voteapp


  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - voteapp


  voting-app:
    image: gaiadocker/example-voting-app-vote:good
    ports:
      - 80
    networks:
      - voteapp
    depends_on:
      - redis


  result-app:
    image: gaiadocker/example-voting-app-result:latest
    ports:
      - 80
    networks:
      - voteapp
    depends_on:
      - db

  worker:
    image: gaiadocker/example-voting-app-worker:latest
    networks:
      voteapp:
        aliases:
          - workers
    depends_on:
      - db
      - redis


networks:
    voteapp:

volumes:
  db-data: